comstar_entity_audit_home:
    pattern: /{page}
    defaults:
        _controller: ComstarEntityAuditBundle:Audit:index
        page: 1
    requirements:
        page: \d+

comstar_entity_audit_viewrevision:
    pattern: /viewrev/{rev}
    defaults:
        _controller: ComstarEntityAuditBundle:Audit:viewRevision
    requirements:
        rev: \d+

comstar_entity_audit_viewentity_detail:
    pattern: /viewent/{className}/{id}/{rev}
    defaults:
        _controller: ComstarEntityAuditBundle:Audit:viewDetail
    requirements:
        rev: \d+

comstar_entity_audit_viewentity:
    pattern: /viewent/{className}/{id}
    defaults:
        _controller: ComstarEntityAuditBundle:Audit:viewEntity

comstar_entity_audit_compare:
    pattern: /compare/{className}/{id}/{oldRev}/{newRev}
    defaults:
        _controller: ComstarEntityAuditBundle:Audit:compare
        oldRev: ~
        newRev: ~